import os
import re
import argparse
import json
from dataclasses import dataclass, field
from typing import List, Dict

@dataclass
class Issue:
    rule: str
    weight: int
    line: int
    message: str

@dataclass
class FileReport:
    file_path: str
    score: int = 0
    issues: List[Issue] = field(default_factory=list)
    token_estimate: int = 0
    requires_chunking: bool = False

class AIDebtScanner:
    def __init__(self, target_dir):
        self.target_dir = target_dir
        self.reports = []
        self.chunk_threshold = 1000 # Configurable tokens threshold
        self.rules = {
            'large_file': {'limit': 300, 'weight': 20},
            'large_function': {'limit': 50, 'weight': 15},
            'complexity': {'limit': 10, 'weight': 15},
            'todo_leftover': {'pattern': r'TODO|FIXME', 'weight': 5},
            'debug_leftover': {'pattern': r'console\.log|print\(|debugger', 'weight': 5},
            'empty_catch': {'pattern': r'catch\s*\(.*?\)\s*\{\s*(//.*|/\*.*?\*/|\s)*\}|except\s*.*:\s*pass', 'weight': 10},
            'generic_exception': {'pattern': r'except Exception:|catch\s*\(Exception', 'weight': 8},
            'magic_numbers': {'pattern': r'(?<!\w)[0-9]{2,}(?!\w)', 'weight': 5},
            'commented_code': {'pattern': r'^\s*#\s*(def|if|for|class|import)\s', 'weight': 15},
            'ai_artifact': {'pattern': r'as an AI model|I can help with|generated by|certainly!|here is the code', 'weight': 30},
            'ts_any': {'pattern': r':\s*any\b|as\s+any\b', 'weight': 12},
            'deep_nesting': {'pattern': r'^\s{12,}(if|for|while|switch)', 'weight': 10},
        }

    def scan_file(self, file_path):
        report = FileReport(file_path=file_path)
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                lines = content.splitlines()
            
            report.token_estimate = len(content) // 4
            if report.token_estimate > self.chunk_threshold:
                report.requires_chunking = True

            # 1. Structural Analysis (Whole Content)
            # Empty Catch / Except pass (Multiline)
            for match in re.finditer(self.rules['empty_catch']['pattern'], content, re.MULTILINE | re.DOTALL):
                line_num = content[:match.start()].count('\n') + 1
                report.issues.append(Issue('EMPTY_CATCH', 10, line_num, "Empty or comment-only catch/except block"))
                report.score += 10

            # 2. Line-by-Line Analysis
            for idx, line in enumerate(lines):
                line_num = idx + 1
                
                # AI Artifacts
                if re.search(self.rules['ai_artifact']['pattern'], line, re.IGNORECASE):
                    report.issues.append(Issue('AI_ARTIFACT', 30, line_num, "AI conversational noise detected"))
                    report.score += 30

                # TS Any
                if file_path.endswith(('.ts', '.tsx')) and re.search(self.rules['ts_any']['pattern'], line):
                    report.issues.append(Issue('TS_ANY_ABUSE', 12, line_num, "Avoid 'any' type"))
                    report.score += 12

                # Deep Nesting
                if re.search(self.rules['deep_nesting']['pattern'], line):
                    report.issues.append(Issue('DEEP_NESTING', 10, line_num, "Deeply nested logic"))
                    report.score += 10

                # Others
                for rule_name in ['todo_leftover', 'debug_leftover', 'generic_exception', 'magic_numbers']:
                    if re.search(self.rules[rule_name]['pattern'], line):
                        report.issues.append(Issue(rule_name.upper(), self.rules[rule_name]['weight'], line_num, f"Detected {rule_name}"))
                        report.score += self.rules[rule_name]['weight']

            # Commented code check
            commented_lines = sum(1 for line in lines if re.search(self.rules['commented_code']['pattern'], line))
            if commented_lines > 3:
                report.issues.append(Issue('COMMENTED_LOGIC', 15, 0, "Suspicious blocks of commented-out code"))
                report.score += 15

            if len(lines) > self.rules['large_file']['limit']:
                report.issues.append(Issue('LARGE_FILE', 20, 0, f"File exceeds {self.rules['large_file']['limit']} lines"))
                report.score += 20

            self._analyze_functions(lines, report, file_path)
            report.score = min(report.score, 100)
            return report
        except Exception as e:
            return None

    def _analyze_functions(self, lines, report, file_path):
        func_start = -1
        if file_path.endswith('.py'):
            for idx, line in enumerate(lines):
                if line.strip().startswith('def '):
                    if func_start != -1:
                        func_len = idx - func_start
                        if func_len > self.rules['large_function']['limit']:
                            report.issues.append(Issue('LARGE_FUNCTION', 15, func_start+1, f"Function has {func_len} lines"))
                            report.score += 15
                    func_start = idx
        elif file_path.endswith(('.ts', '.js', '.tsx', '.jsx', '.go', '.rs')):
            # Heuristic: count lines between braces if applicable
            pass

    def run(self):
        exclude_dirs = {'.git', 'node_modules', 'venv', '.venv', '__pycache__', 'dist', 'build'}
        extensions = {'.py', '.ts', '.js', '.tsx', '.jsx', '.go', '.rs', '.java', '.cpp'}
        
        if os.path.isfile(self.target_dir):
            report = self.scan_file(self.target_dir)
            if report and report.score > 0:
                self.reports.append(report)
            return

        for root, dirs, files in os.walk(self.target_dir):
            dirs[:] = [d for d in dirs if d not in exclude_dirs]
            for file in files:
                if any(file.endswith(ext) for ext in extensions):
                    file_path = os.path.join(root, file)
                    report = self.scan_file(file_path)
                    if report and report.score > 0:
                        self.reports.append(report)

    def to_json(self):
        return json.dumps([r.__dict__ for r in self.reports], default=lambda o: o.__dict__ if hasattr(o, '__dict__') else str(o), indent=2)

    def to_toon(self):
        """Official Token-Oriented Object Notation (TOON) implementation."""
        lines = [
            "toon: 1.0",
            f"project: {self.target_dir}",
            f"debt_files: {len(self.reports)}",
            ""
        ]
        
        for r in self.reports:
            # File header
            lines.append(f"file: {r.file_path}")
            lines.append(f"  score: {r.score}")
            lines.append(f"  tokens: {r.token_estimate}")
            if r.requires_chunking:
                lines.append("  chunk: true")
            
            # Hotspots in Tabular TOON format
            if r.issues:
                lines.append(f"  hotspots[{len(r.issues)}]{{line,rule,msg}}:")
                for issue in r.issues:
                    # Escape commas in messages to maintain CSV integrity
                    clean_msg = issue.message.replace(",", ";")
                    lines.append(f"    {issue.line},{issue.rule.upper()},{clean_msg}")
            lines.append("") # Separator

        return "\n".join(lines)

    def print_summary(self):
        if not self.reports:
            print("No AI technical debt detected! 🚀")
            return
        
        avg_score = sum(r.score for r in self.reports) / len(self.reports)
        print(f"\nAI DEBT SCAN REPORT | Avg Score: {avg_score:.2f}")
        for r in sorted(self.reports, key=lambda x: x.score, reverse=True)[:5]:
            print(f"[{r.score:3}] {r.file_path} ({len(r.issues)} issues)")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('path', nargs='?', default='.', help='Path to scan')
    parser.add_argument('--json', action='store_true', help='Output in JSON format')
    parser.add_argument('--toon', action='store_true', help='Output in TOON (Token-Oriented Object Notation) format')
    args = parser.parse_args()
    
    scanner = AIDebtScanner(args.path)
    scanner.run()
    
    if args.toon:
        print(scanner.to_toon())
    elif args.json:
        print(scanner.to_json())
    else:
        scanner.print_summary()
